export function getTableColumns(featureKey) {
  const configs = {
    vehicleModels: [
      { field: 'name', label: 'Name' },
      { field: 'manufacturer', label: 'Manufacturer' },
      { field: 'type', label: 'Type' },
      { field: 'autonomyLevel', label: 'Autonomy Level' },
      { field: 'maxSpeed', label: 'Max Speed (km/h)' },
      { field: 'sensorCount', label: 'Sensors' },
      { field: 'status', label: 'Status' },
    ],
    sensorConfigs: [
      { field: 'name', label: 'Name' },
      { field: 'type', label: 'Type' },
      { field: 'manufacturer', label: 'Manufacturer' },
      { field: 'range', label: 'Range (m)' },
      { field: 'accuracy', label: 'Accuracy' },
      { field: 'fieldOfView', label: 'FOV' },
      { field: 'status', label: 'Status' },
    ],
    drivingScenarios: [
      { field: 'name', label: 'Name' },
      { field: 'category', label: 'Category' },
      { field: 'difficulty', label: 'Difficulty' },
      { field: 'weatherCondition', label: 'Weather' },
      { field: 'trafficDensity', label: 'Traffic' },
      { field: 'roadType', label: 'Road Type' },
      { field: 'status', label: 'Status' },
    ],
    trainingSessions: [
      { field: 'name', label: 'Name' },
      { field: 'modelName', label: 'Model' },
      { field: 'algorithm', label: 'Algorithm' },
      { field: 'epochs', label: 'Epochs' },
      { field: 'accuracy', label: 'Accuracy' },
      { field: 'loss', label: 'Loss' },
      { field: 'status', label: 'Status' },
    ],
    simulationResults: [
      { field: 'name', label: 'Name' },
      { field: 'scenarioName', label: 'Scenario' },
      { field: 'vehicleName', label: 'Vehicle' },
      { field: 'successRate', label: 'Success Rate' },
      { field: 'collisions', label: 'Collisions' },
      { field: 'grade', label: 'Grade' },
      { field: 'status', label: 'Status' },
    ],
    routePlans: [
      { field: 'name', label: 'Name' },
      { field: 'origin', label: 'Origin' },
      { field: 'destination', label: 'Destination' },
      { field: 'distance', label: 'Distance (km)' },
      { field: 'algorithm', label: 'Algorithm' },
      { field: 'optimizationType', label: 'Optimization' },
      { field: 'status', label: 'Status' },
    ],
    objectDetections: [
      { field: 'name', label: 'Name' },
      { field: 'objectType', label: 'Object Type' },
      { field: 'detectionModel', label: 'Model' },
      { field: 'confidence', label: 'Confidence' },
      { field: 'precision', label: 'Precision' },
      { field: 'inferenceTime', label: 'Inference (ms)' },
      { field: 'status', label: 'Status' },
    ],
    trafficSimulations: [
      { field: 'name', label: 'Name' },
      { field: 'scenarioType', label: 'Type' },
      { field: 'vehicleCount', label: 'Vehicles' },
      { field: 'pedestrianCount', label: 'Pedestrians' },
      { field: 'congestionLevel', label: 'Congestion' },
      { field: 'intersections', label: 'Intersections' },
      { field: 'status', label: 'Status' },
    ],
    weatherSimulations: [
      { field: 'name', label: 'Name' },
      { field: 'weatherType', label: 'Weather Type' },
      { field: 'intensity', label: 'Intensity' },
      { field: 'visibility', label: 'Visibility (m)' },
      { field: 'windSpeed', label: 'Wind (km/h)' },
      { field: 'roadCondition', label: 'Road Condition' },
      { field: 'status', label: 'Status' },
    ],
    safetyMetrics: [
      { field: 'name', label: 'Name' },
      { field: 'category', label: 'Category' },
      { field: 'score', label: 'Score' },
      { field: 'passRate', label: 'Pass Rate' },
      { field: 'riskLevel', label: 'Risk Level' },
      { field: 'standard', label: 'Standard' },
      { field: 'status', label: 'Status' },
    ],
    fleetVehicles: [
      { field: 'name', label: 'Name' },
      { field: 'vehicleId', label: 'Vehicle ID' },
      { field: 'model', label: 'Model' },
      { field: 'location', label: 'Location' },
      { field: 'mileage', label: 'Mileage (km)' },
      { field: 'batteryLevel', label: 'Battery' },
      { field: 'operationalStatus', label: 'Status' },
    ],
    mapEnvironments: [
      { field: 'name', label: 'Name' },
      { field: 'environmentType', label: 'Type' },
      { field: 'size', label: 'Size (km²)' },
      { field: 'complexity', label: 'Complexity' },
      { field: 'laneCount', label: 'Lanes' },
      { field: 'region', label: 'Region' },
      { field: 'status', label: 'Status' },
    ],
    aiModels: [
      { field: 'name', label: 'Name' },
      { field: 'version', label: 'Version' },
      { field: 'framework', label: 'Framework' },
      { field: 'architecture', label: 'Architecture' },
      { field: 'accuracy', label: 'Accuracy' },
      { field: 'inferenceSpeed', label: 'Inference (ms)' },
      { field: 'status', label: 'Status' },
    ],
    collisionAnalyses: [
      { field: 'name', label: 'Name' },
      { field: 'collisionType', label: 'Type' },
      { field: 'severity', label: 'Severity' },
      { field: 'speed', label: 'Speed (km/h)' },
      { field: 'cause', label: 'Cause' },
      { field: 'avoidable', label: 'Avoidable' },
      { field: 'status', label: 'Status' },
    ],
    regulatoryCompliances: [
      { field: 'name', label: 'Name' },
      { field: 'regulation', label: 'Regulation' },
      { field: 'jurisdiction', label: 'Jurisdiction' },
      { field: 'saeLevel', label: 'SAE Level' },
      { field: 'complianceStatus', label: 'Compliance' },
      { field: 'certificationBody', label: 'Certification Body' },
      { field: 'status', label: 'Status' },
    ],
  };
  return configs[featureKey] || [];
}

export function getFormFields(featureKey) {
  const configs = {
    vehicleModels: [
      { field: 'name', label: 'Vehicle Name', type: 'text', required: true },
      { field: 'manufacturer', label: 'Manufacturer', type: 'text', required: true },
      { field: 'type', label: 'Type', type: 'select', required: true, options: ['Sedan', 'SUV', 'Van', 'Truck', 'Bus', 'Shuttle', 'Compact', 'Pod', 'Sports', 'Ambulance', 'Tractor', 'Boat', 'VTOL', 'Mining Vehicle'] },
      { field: 'autonomyLevel', label: 'Autonomy Level (0-5)', type: 'number', required: true },
      { field: 'maxSpeed', label: 'Max Speed (km/h)', type: 'number' },
      { field: 'sensorCount', label: 'Sensor Count', type: 'number' },
      { field: 'status', label: 'Status', type: 'select', options: ['active', 'testing', 'prototype', 'inactive'] },
      { field: 'description', label: 'Description', type: 'textarea', fullWidth: true },
    ],
    sensorConfigs: [
      { field: 'name', label: 'Sensor Name', type: 'text', required: true },
      { field: 'type', label: 'Type', type: 'select', required: true, options: ['LiDAR', 'Camera', 'Radar', 'Ultrasonic', 'Thermal Camera', 'GPS/GNSS', 'IMU'] },
      { field: 'manufacturer', label: 'Manufacturer', type: 'text' },
      { field: 'range', label: 'Range (m)', type: 'number' },
      { field: 'accuracy', label: 'Accuracy (%)', type: 'number' },
      { field: 'fieldOfView', label: 'Field of View (°)', type: 'number' },
      { field: 'resolution', label: 'Resolution', type: 'text' },
      { field: 'refreshRate', label: 'Refresh Rate (Hz)', type: 'number' },
      { field: 'status', label: 'Status', type: 'select', options: ['active', 'testing', 'inactive'] },
      { field: 'description', label: 'Description', type: 'textarea', fullWidth: true },
    ],
    drivingScenarios: [
      { field: 'name', label: 'Scenario Name', type: 'text', required: true },
      { field: 'category', label: 'Category', type: 'select', required: true, options: ['Highway', 'Urban', 'Rural', 'Weather', 'Emergency', 'Parking', 'Infrastructure'] },
      { field: 'difficulty', label: 'Difficulty', type: 'select', options: ['Easy', 'Medium', 'Hard', 'Extreme'] },
      { field: 'weatherCondition', label: 'Weather Condition', type: 'select', options: ['Clear', 'Light Rain', 'Heavy Rain', 'Snow', 'Fog', 'Snow Storm', 'Extreme Heat', 'Indoor'] },
      { field: 'trafficDensity', label: 'Traffic Density', type: 'select', options: ['Very Low', 'Low', 'Medium', 'High', 'Very High'] },
      { field: 'roadType', label: 'Road Type', type: 'text' },
      { field: 'duration', label: 'Duration (seconds)', type: 'number' },
      { field: 'status', label: 'Status', type: 'select', options: ['active', 'inactive', 'draft'] },
      { field: 'description', label: 'Description', type: 'textarea', fullWidth: true },
    ],
    trainingSessions: [
      { field: 'name', label: 'Session Name', type: 'text', required: true },
      { field: 'modelName', label: 'Model Name', type: 'text', required: true },
      { field: 'algorithm', label: 'Algorithm', type: 'select', options: ['Deep CNN', 'ResNet-152', 'PPO', 'YOLO-v8', 'EfficientNet', 'Transformer', 'LSTM', 'DeepLab-v3+', 'PointNet++', 'GAN', 'Domain Adaptation', 'MAPPO', 'Imitation Learning', 'Voxel Transformer', 'Attention Fusion'] },
      { field: 'epochs', label: 'Epochs', type: 'number' },
      { field: 'learningRate', label: 'Learning Rate', type: 'number' },
      { field: 'accuracy', label: 'Accuracy (%)', type: 'number' },
      { field: 'loss', label: 'Loss', type: 'number' },
      { field: 'status', label: 'Status', type: 'select', options: ['pending', 'running', 'completed', 'failed', 'queued'] },
      { field: 'description', label: 'Description', type: 'textarea', fullWidth: true },
    ],
    simulationResults: [
      { field: 'name', label: 'Test Name', type: 'text', required: true },
      { field: 'scenarioName', label: 'Scenario', type: 'text' },
      { field: 'vehicleName', label: 'Vehicle', type: 'text' },
      { field: 'successRate', label: 'Success Rate (%)', type: 'number' },
      { field: 'collisions', label: 'Collisions', type: 'number' },
      { field: 'nearMisses', label: 'Near Misses', type: 'number' },
      { field: 'avgSpeed', label: 'Avg Speed (km/h)', type: 'number' },
      { field: 'totalDistance', label: 'Total Distance (km)', type: 'number' },
      { field: 'duration', label: 'Duration (seconds)', type: 'number' },
      { field: 'grade', label: 'Grade', type: 'select', options: ['A+', 'A', 'A-', 'B+', 'B', 'B-', 'C+', 'C', 'D', 'F'] },
      { field: 'status', label: 'Status', type: 'select', options: ['completed', 'running', 'failed', 'pending'] },
      { field: 'description', label: 'Description', type: 'textarea', fullWidth: true },
    ],
    routePlans: [
      { field: 'name', label: 'Route Name', type: 'text', required: true },
      { field: 'origin', label: 'Origin', type: 'text', required: true },
      { field: 'destination', label: 'Destination', type: 'text', required: true },
      { field: 'distance', label: 'Distance (km)', type: 'number' },
      { field: 'estimatedTime', label: 'Est. Time (min)', type: 'number' },
      { field: 'algorithm', label: 'Algorithm', type: 'select', options: ['A* Search', 'Dijkstra', 'BFS', 'TSP Solver', 'VRP Solver', 'Emergency Routing', 'Contraction Hierarchies', 'Priority Routing', 'Circular Route', 'Modified A*'] },
      { field: 'waypoints', label: 'Waypoints', type: 'number' },
      { field: 'optimizationType', label: 'Optimization', type: 'select', options: ['Fastest', 'Shortest', 'Scenic', 'Balanced', 'Multi-stop', 'Heavy Vehicle', 'Low Traffic', 'Multi-pickup', 'Avoid Crowds', 'Performance', 'Smooth Ride'] },
      { field: 'status', label: 'Status', type: 'select', options: ['planned', 'active', 'completed', 'cancelled'] },
      { field: 'description', label: 'Description', type: 'textarea', fullWidth: true },
    ],
    objectDetections: [
      { field: 'name', label: 'Detection Name', type: 'text', required: true },
      { field: 'objectType', label: 'Object Type', type: 'select', required: true, options: ['Pedestrian', 'Vehicle', 'Cyclist', 'Traffic Sign', 'Traffic Light', 'Lane Marking', 'Construction Object', 'Animal', 'Road Obstacle', 'Emergency Vehicle', 'Road Defect', 'Crosswalk', 'Speed Bump', 'Road Debris', 'Parking Space'] },
      { field: 'detectionModel', label: 'Detection Model', type: 'text' },
      { field: 'confidence', label: 'Confidence (%)', type: 'number' },
      { field: 'precision', label: 'Precision (%)', type: 'number' },
      { field: 'recall', label: 'Recall (%)', type: 'number' },
      { field: 'f1Score', label: 'F1 Score', type: 'number' },
      { field: 'inferenceTime', label: 'Inference Time (ms)', type: 'number' },
      { field: 'status', label: 'Status', type: 'select', options: ['active', 'testing', 'inactive'] },
      { field: 'description', label: 'Description', type: 'textarea', fullWidth: true },
    ],
    trafficSimulations: [
      { field: 'name', label: 'Simulation Name', type: 'text', required: true },
      { field: 'scenarioType', label: 'Scenario Type', type: 'select', required: true, options: ['Rush Hour', 'Highway', 'Residential', 'Event', 'School Zone', 'Emergency', 'Night', 'Construction', 'Incident', 'Commercial', 'Weather Impact', 'Transit', 'Holiday', 'Parking', 'Smart City'] },
      { field: 'vehicleCount', label: 'Vehicle Count', type: 'number' },
      { field: 'pedestrianCount', label: 'Pedestrian Count', type: 'number' },
      { field: 'avgFlowRate', label: 'Avg Flow Rate', type: 'number' },
      { field: 'congestionLevel', label: 'Congestion Level', type: 'select', options: ['Very Low', 'Low', 'Medium', 'High', 'Very High', 'Extreme'] },
      { field: 'intersections', label: 'Intersections', type: 'number' },
      { field: 'duration', label: 'Duration (sec)', type: 'number' },
      { field: 'status', label: 'Status', type: 'select', options: ['active', 'inactive', 'running'] },
      { field: 'description', label: 'Description', type: 'textarea', fullWidth: true },
    ],
    weatherSimulations: [
      { field: 'name', label: 'Simulation Name', type: 'text', required: true },
      { field: 'weatherType', label: 'Weather Type', type: 'select', required: true, options: ['Clear', 'Rain', 'Thunderstorm', 'Fog', 'Snow', 'Blizzard', 'Ice Storm', 'Sandstorm', 'Tropical Rain', 'Mist', 'Hail', 'Extreme Heat', 'Wind', 'Sleet', 'Post-Storm'] },
      { field: 'intensity', label: 'Intensity', type: 'select', options: ['None', 'Light', 'Moderate', 'Heavy', 'Extreme'] },
      { field: 'visibility', label: 'Visibility (m)', type: 'number' },
      { field: 'windSpeed', label: 'Wind Speed (km/h)', type: 'number' },
      { field: 'precipitation', label: 'Precipitation (mm/hr)', type: 'number' },
      { field: 'temperature', label: 'Temperature (°C)', type: 'number' },
      { field: 'roadCondition', label: 'Road Condition', type: 'text' },
      { field: 'status', label: 'Status', type: 'select', options: ['active', 'inactive'] },
      { field: 'description', label: 'Description', type: 'textarea', fullWidth: true },
    ],
    safetyMetrics: [
      { field: 'name', label: 'Metric Name', type: 'text', required: true },
      { field: 'category', label: 'Category', type: 'select', required: true, options: ['Collision Prevention', 'Pedestrian Protection', 'Braking Systems', 'Lane Assistance', 'System Reliability', 'Visibility', 'Environmental', 'Cybersecurity', 'Functional Safety', 'Connectivity', 'System Recovery', 'Operational Domain', 'Transition Safety', 'Social Driving', 'Availability'] },
      { field: 'score', label: 'Score', type: 'number' },
      { field: 'maxScore', label: 'Max Score', type: 'number' },
      { field: 'testCount', label: 'Test Count', type: 'number' },
      { field: 'passRate', label: 'Pass Rate (%)', type: 'number' },
      { field: 'riskLevel', label: 'Risk Level', type: 'select', options: ['Very Low', 'Low', 'Medium', 'High', 'Critical'] },
      { field: 'standard', label: 'Standard', type: 'text' },
      { field: 'status', label: 'Status', type: 'select', options: ['active', 'inactive'] },
      { field: 'description', label: 'Description', type: 'textarea', fullWidth: true },
    ],
    fleetVehicles: [
      { field: 'name', label: 'Vehicle Name', type: 'text', required: true },
      { field: 'vehicleId', label: 'Vehicle ID', type: 'text' },
      { field: 'model', label: 'Model', type: 'text' },
      { field: 'location', label: 'Location', type: 'text' },
      { field: 'mileage', label: 'Mileage (km)', type: 'number' },
      { field: 'batteryLevel', label: 'Battery Level (%)', type: 'number' },
      { field: 'operationalStatus', label: 'Operational Status', type: 'select', options: ['operational', 'maintenance', 'charging', 'standby', 'docked', 'grounded'] },
      { field: 'status', label: 'Status', type: 'select', options: ['active', 'testing', 'retired'] },
      { field: 'description', label: 'Description', type: 'textarea', fullWidth: true },
    ],
    mapEnvironments: [
      { field: 'name', label: 'Environment Name', type: 'text', required: true },
      { field: 'environmentType', label: 'Type', type: 'select', required: true, options: ['Urban', 'Highway', 'Dense Urban', 'Desert', 'Mountain', 'Suburban', 'Industrial', 'Campus', 'Smart City', 'Winter', 'Chaotic Urban', 'Airport', 'Rural', 'Tropical Urban'] },
      { field: 'size', label: 'Size (km²)', type: 'number' },
      { field: 'complexity', label: 'Complexity', type: 'select', options: ['Low', 'Medium', 'High', 'Very High', 'Extreme'] },
      { field: 'laneCount', label: 'Lane Count', type: 'number' },
      { field: 'hasIntersections', label: 'Has Intersections', type: 'select', options: ['true', 'false'] },
      { field: 'hasPedestrians', label: 'Has Pedestrians', type: 'select', options: ['true', 'false'] },
      { field: 'region', label: 'Region', type: 'text' },
      { field: 'status', label: 'Status', type: 'select', options: ['active', 'inactive', 'draft'] },
      { field: 'description', label: 'Description', type: 'textarea', fullWidth: true },
    ],
    aiModels: [
      { field: 'name', label: 'Model Name', type: 'text', required: true },
      { field: 'version', label: 'Version', type: 'text' },
      { field: 'framework', label: 'Framework', type: 'select', options: ['PyTorch', 'TensorFlow', 'TensorFlow Lite', 'JAX', 'C++ / TensorRT', 'Unity ML', 'ONNX'] },
      { field: 'architecture', label: 'Architecture', type: 'text' },
      { field: 'parameters', label: 'Parameters', type: 'text' },
      { field: 'accuracy', label: 'Accuracy (%)', type: 'number' },
      { field: 'inferenceSpeed', label: 'Inference Speed (ms)', type: 'number' },
      { field: 'trainedOn', label: 'Trained On', type: 'text' },
      { field: 'status', label: 'Status', type: 'select', options: ['production', 'testing', 'research', 'deprecated'] },
      { field: 'description', label: 'Description', type: 'textarea', fullWidth: true },
    ],
    collisionAnalyses: [
      { field: 'name', label: 'Incident Name', type: 'text', required: true },
      { field: 'collisionType', label: 'Collision Type', type: 'select', required: true, options: ['Rear-End', 'Side-Swipe', 'T-Bone', 'Head-On', 'Pedestrian', 'Cyclist', 'Animal', 'Fixed Object', 'Single Vehicle', 'Multi-Vehicle', 'Side-Impact', 'Door Zone', 'Low-Speed Contact', 'Rear-End (Caused)'] },
      { field: 'severity', label: 'Severity', type: 'select', options: ['Minor', 'Moderate', 'Severe', 'Critical', 'Fatal'] },
      { field: 'speed', label: 'Speed (km/h)', type: 'number' },
      { field: 'cause', label: 'Cause', type: 'text' },
      { field: 'avoidable', label: 'Avoidable', type: 'select', options: ['true', 'false'] },
      { field: 'vehicleInvolved', label: 'Vehicle Involved', type: 'text' },
      { field: 'location', label: 'Location', type: 'text' },
      { field: 'status', label: 'Status', type: 'select', options: ['analyzed', 'pending', 'investigating'] },
      { field: 'recommendations', label: 'Recommendations', type: 'textarea', fullWidth: true },
      { field: 'description', label: 'Description', type: 'textarea', fullWidth: true },
    ],
    regulatoryCompliances: [
      { field: 'name', label: 'Compliance Name', type: 'text', required: true },
      { field: 'regulation', label: 'Regulation', type: 'text', required: true },
      { field: 'jurisdiction', label: 'Jurisdiction', type: 'text' },
      { field: 'saeLevel', label: 'SAE Level', type: 'select', options: ['All Levels', 'Level 2', 'Level 2+', 'Level 3', 'Level 3+', 'Level 4', 'Level 4+', 'Level 5'] },
      { field: 'complianceStatus', label: 'Compliance Status', type: 'select', options: ['Compliant', 'In Progress', 'Pending', 'Non-Compliant'] },
      { field: 'certificationBody', label: 'Certification Body', type: 'text' },
      { field: 'status', label: 'Status', type: 'select', options: ['active', 'inactive', 'expired'] },
      { field: 'description', label: 'Description', type: 'textarea', fullWidth: true },
    ],
  };
  return configs[featureKey] || [];
}
