const bcrypt = require('bcryptjs');
const {
  sequelize, User, VehicleModel, SensorConfig, DrivingScenario,
  TrainingSession, SimulationResult, RoutePlan, ObjectDetection,
  TrafficSimulation, WeatherSimulation, SafetyMetric, FleetVehicle,
  MapEnvironment, AIModel, CollisionAnalysis, RegulatoryCompliance
} = require('../models');

async function seed() {
  try {
    await sequelize.sync({ force: true });
    console.log('Database synced.');

    // Users
    const hashedPassword = await bcrypt.hash('admin123', 10);
    await User.bulkCreate([
      { email: 'admin@avsimulator.com', password: hashedPassword, name: 'Admin User', role: 'admin' },
      { email: 'engineer@avsimulator.com', password: hashedPassword, name: 'Lead Engineer', role: 'engineer' },
      { email: 'analyst@avsimulator.com', password: hashedPassword, name: 'Data Analyst', role: 'analyst' }
    ]);
    console.log('Users seeded.');

    // Vehicle Models (15)
    await VehicleModel.bulkCreate([
      { name: 'AutoPilot X1', manufacturer: 'TechDrive', type: 'Sedan', autonomyLevel: 4, maxSpeed: 200, sensorCount: 12, status: 'active', description: 'High-performance autonomous sedan with Level 4 capabilities', specs: { weight: 1800, range: 500, battery: '100kWh' } },
      { name: 'RoboVan Pro', manufacturer: 'TransitAI', type: 'Van', autonomyLevel: 3, maxSpeed: 150, sensorCount: 16, status: 'active', description: 'Commercial delivery van with advanced autonomous features', specs: { weight: 3200, payload: 2000, range: 300 } },
      { name: 'CityBot Compact', manufacturer: 'UrbanMobility', type: 'Compact', autonomyLevel: 5, maxSpeed: 120, sensorCount: 20, status: 'active', description: 'Fully autonomous city vehicle for urban transport', specs: { weight: 1200, passengers: 4, range: 250 } },
      { name: 'FreightMaster 9000', manufacturer: 'HeavyHaul', type: 'Truck', autonomyLevel: 3, maxSpeed: 130, sensorCount: 24, status: 'active', description: 'Long-haul autonomous truck for freight transport', specs: { weight: 18000, payload: 25000, range: 800 } },
      { name: 'SwiftShuttle S2', manufacturer: 'TechDrive', type: 'Shuttle', autonomyLevel: 4, maxSpeed: 80, sensorCount: 18, status: 'active', description: 'Autonomous shuttle for campus and airport transport', specs: { weight: 4500, passengers: 12, range: 200 } },
      { name: 'NightOwl EV', manufacturer: 'DarkDrive', type: 'SUV', autonomyLevel: 4, maxSpeed: 180, sensorCount: 14, status: 'testing', description: 'Night-optimized autonomous SUV with enhanced low-light sensors', specs: { weight: 2200, range: 450, nightVision: true } },
      { name: 'MicroPod Alpha', manufacturer: 'UrbanMobility', type: 'Pod', autonomyLevel: 5, maxSpeed: 60, sensorCount: 8, status: 'active', description: 'Single-passenger autonomous pod for last-mile transport', specs: { weight: 600, passengers: 1, range: 100 } },
      { name: 'AgroDrive T4', manufacturer: 'FarmTech', type: 'Tractor', autonomyLevel: 3, maxSpeed: 45, sensorCount: 10, status: 'active', description: 'Autonomous agricultural vehicle for farming operations', specs: { weight: 8000, fieldCoverage: '50 acres/hr' } },
      { name: 'CoastGuard Marine', manufacturer: 'AquaNav', type: 'Boat', autonomyLevel: 2, maxSpeed: 55, sensorCount: 12, status: 'prototype', description: 'Semi-autonomous marine vessel for coastal patrol', specs: { weight: 5000, range: 200, waterproof: 'IP68' } },
      { name: 'SkyCab Drone', manufacturer: 'AeroTransit', type: 'VTOL', autonomyLevel: 4, maxSpeed: 250, sensorCount: 22, status: 'testing', description: 'Vertical take-off autonomous air taxi', specs: { weight: 1500, passengers: 2, altitude: 3000 } },
      { name: 'Rally Runner R8', manufacturer: 'SpeedAI', type: 'Sports', autonomyLevel: 3, maxSpeed: 320, sensorCount: 16, status: 'active', description: 'Autonomous sports car for racing simulation', specs: { weight: 1400, hp: 600, acceleration: '0-100 in 2.8s' } },
      { name: 'MedEvac One', manufacturer: 'HealthTransit', type: 'Ambulance', autonomyLevel: 4, maxSpeed: 160, sensorCount: 20, status: 'active', description: 'Autonomous emergency medical transport vehicle', specs: { weight: 3800, medEquipment: true, sirens: true } },
      { name: 'MineBoss Heavy', manufacturer: 'IndustrialAI', type: 'Mining Vehicle', autonomyLevel: 3, maxSpeed: 40, sensorCount: 14, status: 'active', description: 'Autonomous mining vehicle for underground operations', specs: { weight: 25000, payload: 50000, dustProof: true } },
      { name: 'ParkPilot EV2', manufacturer: 'TechDrive', type: 'Sedan', autonomyLevel: 2, maxSpeed: 180, sensorCount: 8, status: 'active', description: 'Level 2 autonomous sedan with advanced parking features', specs: { weight: 1600, range: 400, parkingAssist: true } },
      { name: 'BusBot Metro', manufacturer: 'TransitAI', type: 'Bus', autonomyLevel: 4, maxSpeed: 100, sensorCount: 28, status: 'active', description: 'Full-size autonomous public transit bus', specs: { weight: 12000, passengers: 60, range: 350 } }
    ]);
    console.log('Vehicle Models seeded.');

    // Sensor Configurations (15)
    await SensorConfig.bulkCreate([
      { name: 'Velodyne VLP-128', type: 'LiDAR', manufacturer: 'Velodyne', range: 300, accuracy: 99.2, fieldOfView: 360, resolution: '128 channels', refreshRate: 20, status: 'active', description: 'Ultra-high resolution 128-channel spinning LiDAR', specs: { channels: 128, wavelength: '905nm' } },
      { name: 'Luminar Iris', type: 'LiDAR', manufacturer: 'Luminar', range: 600, accuracy: 99.5, fieldOfView: 120, resolution: '300 pts/sq deg', refreshRate: 15, status: 'active', description: 'Long-range LiDAR for highway autonomous driving', specs: { wavelength: '1550nm', eyeSafe: true } },
      { name: 'Mobileye EyeQ6', type: 'Camera', manufacturer: 'Mobileye', range: 250, accuracy: 97.8, fieldOfView: 100, resolution: '8MP', refreshRate: 60, status: 'active', description: 'Advanced forward-facing vision camera system', specs: { hdr: true, nightVision: true } },
      { name: 'Continental ARS540', type: 'Radar', manufacturer: 'Continental', range: 300, accuracy: 96.5, fieldOfView: 120, resolution: '4D imaging', refreshRate: 25, status: 'active', description: '4D imaging radar for all-weather detection', specs: { frequency: '77GHz', dopplerRes: '0.1 m/s' } },
      { name: 'Bosch USS6', type: 'Ultrasonic', manufacturer: 'Bosch', range: 6, accuracy: 95.0, fieldOfView: 120, resolution: '1cm', refreshRate: 40, status: 'active', description: 'Short-range ultrasonic sensors for parking assistance', specs: { frequency: '48kHz', waterproof: true } },
      { name: 'FLIR ADK', type: 'Thermal Camera', manufacturer: 'FLIR', range: 200, accuracy: 94.5, fieldOfView: 75, resolution: '640x512', refreshRate: 30, status: 'active', description: 'Thermal imaging camera for pedestrian detection in dark conditions', specs: { spectralRange: '8-14μm', nuc: true } },
      { name: 'Ouster OS1-128', type: 'LiDAR', manufacturer: 'Ouster', range: 240, accuracy: 98.8, fieldOfView: 360, resolution: '128 channels', refreshRate: 20, status: 'active', description: 'Digital spinning LiDAR with multi-beam flash architecture', specs: { channels: 128, digital: true } },
      { name: 'ZF ProAI GPS', type: 'GPS/GNSS', manufacturer: 'ZF', range: 0, accuracy: 99.9, fieldOfView: 360, resolution: 'RTK 2cm', refreshRate: 100, status: 'active', description: 'High-precision RTK GPS for centimeter-level positioning', specs: { rtk: true, multiConstellation: true } },
      { name: 'Hesai AT128', type: 'LiDAR', manufacturer: 'Hesai', range: 200, accuracy: 98.5, fieldOfView: 120, resolution: '128 channels', refreshRate: 10, status: 'active', description: 'Hybrid solid-state LiDAR for ADAS applications', specs: { solidState: true, automotive: true } },
      { name: 'Sony IMX490', type: 'Camera', manufacturer: 'Sony', range: 300, accuracy: 98.0, fieldOfView: 60, resolution: '5.4MP HDR', refreshRate: 60, status: 'active', description: 'High dynamic range automotive image sensor', specs: { hdr: '120dB', ledFlicker: true } },
      { name: 'Arbe Phoenix', type: 'Radar', manufacturer: 'Arbe', range: 350, accuracy: 97.0, fieldOfView: 100, resolution: 'Ultra-HD 4D', refreshRate: 30, status: 'active', description: 'Ultra-high resolution 4D imaging radar with 48x48 array', specs: { channels: 2304, azimuth: '1 deg' } },
      { name: 'InvenSense ICM-42688', type: 'IMU', manufacturer: 'TDK', range: 0, accuracy: 99.5, fieldOfView: 0, resolution: '16-bit', refreshRate: 32000, status: 'active', description: '6-axis inertial measurement unit for vehicle motion tracking', specs: { axes: 6, gyroRange: '2000 dps' } },
      { name: 'Valeo SCALA 2', type: 'LiDAR', manufacturer: 'Valeo', range: 200, accuracy: 98.0, fieldOfView: 150, resolution: '16 layers', refreshRate: 25, status: 'active', description: 'First automotive-grade scanning LiDAR in production', specs: { production: true, autoGrade: true } },
      { name: 'Aptiv SRR', type: 'Radar', manufacturer: 'Aptiv', range: 80, accuracy: 95.5, fieldOfView: 150, resolution: 'Standard', refreshRate: 20, status: 'active', description: 'Short-range radar for blind-spot and cross-traffic detection', specs: { frequency: '77GHz', type: 'SRR' } },
      { name: 'Leopard LI-AR0820', type: 'Camera', manufacturer: 'Leopard Imaging', range: 180, accuracy: 96.8, fieldOfView: 120, resolution: '8.3MP', refreshRate: 30, status: 'active', description: 'Surround view camera module for autonomous vehicles', specs: { surround: true, hdr: true } }
    ]);
    console.log('Sensor Configs seeded.');

    // Driving Scenarios (15)
    await DrivingScenario.bulkCreate([
      { name: 'Highway Cruising', category: 'Highway', difficulty: 'Easy', weatherCondition: 'Clear', trafficDensity: 'Low', roadType: 'Highway', duration: 3600, status: 'active', description: 'Standard highway driving in clear conditions with minimal traffic', parameters: { speedLimit: 120, lanes: 4 } },
      { name: 'Urban Rush Hour', category: 'Urban', difficulty: 'Hard', weatherCondition: 'Clear', trafficDensity: 'Very High', roadType: 'City Street', duration: 1800, status: 'active', description: 'Dense urban traffic during peak commute hours', parameters: { speedLimit: 50, intersections: 20 } },
      { name: 'Rainy Night Drive', category: 'Weather', difficulty: 'Hard', weatherCondition: 'Heavy Rain', trafficDensity: 'Medium', roadType: 'Mixed', duration: 2400, status: 'active', description: 'Night driving through heavy rain with reduced visibility', parameters: { visibility: 50, precipitation: 25 } },
      { name: 'School Zone Navigation', category: 'Urban', difficulty: 'Medium', weatherCondition: 'Clear', trafficDensity: 'Medium', roadType: 'School Zone', duration: 600, status: 'active', description: 'Navigating through active school zones with children present', parameters: { speedLimit: 25, pedestrians: 50 } },
      { name: 'Mountain Pass', category: 'Rural', difficulty: 'Hard', weatherCondition: 'Fog', trafficDensity: 'Low', roadType: 'Mountain Road', duration: 5400, status: 'active', description: 'Winding mountain roads with fog and steep grades', parameters: { elevation: 3000, grade: 8 } },
      { name: 'Construction Zone', category: 'Urban', difficulty: 'Medium', weatherCondition: 'Clear', trafficDensity: 'Medium', roadType: 'Construction', duration: 1200, status: 'active', description: 'Navigating through active construction zones with lane changes', parameters: { cones: true, workers: true } },
      { name: 'Parking Garage', category: 'Parking', difficulty: 'Medium', weatherCondition: 'Indoor', trafficDensity: 'Low', roadType: 'Parking Structure', duration: 300, status: 'active', description: 'Multi-level parking garage navigation and spot finding', parameters: { levels: 5, spots: 500 } },
      { name: 'Emergency Vehicle Response', category: 'Emergency', difficulty: 'Hard', weatherCondition: 'Clear', trafficDensity: 'High', roadType: 'Mixed', duration: 900, status: 'active', description: 'Responding to approaching emergency vehicles in traffic', parameters: { sirens: true, pullOver: true } },
      { name: 'Snow Storm Highway', category: 'Weather', difficulty: 'Extreme', weatherCondition: 'Snow Storm', trafficDensity: 'Low', roadType: 'Highway', duration: 3600, status: 'active', description: 'Highway driving during a severe snow storm', parameters: { visibility: 20, snowRate: 5 } },
      { name: 'Roundabout Navigation', category: 'Urban', difficulty: 'Medium', weatherCondition: 'Clear', trafficDensity: 'Medium', roadType: 'Roundabout', duration: 300, status: 'active', description: 'Multiple roundabout entries and exits with traffic', parameters: { roundabouts: 5, exits: 4 } },
      { name: 'Highway Merge', category: 'Highway', difficulty: 'Medium', weatherCondition: 'Clear', trafficDensity: 'High', roadType: 'Highway On-ramp', duration: 120, status: 'active', description: 'Merging onto busy highway from on-ramp', parameters: { mergeSpeed: 100, gap: 3 } },
      { name: 'Pedestrian Crossing', category: 'Urban', difficulty: 'Medium', weatherCondition: 'Clear', trafficDensity: 'Medium', roadType: 'Crosswalk', duration: 600, status: 'active', description: 'Handling multiple pedestrian crossings and jaywalkers', parameters: { crosswalks: 10, jaywalkers: 5 } },
      { name: 'Tunnel Transit', category: 'Infrastructure', difficulty: 'Medium', weatherCondition: 'Indoor', trafficDensity: 'Medium', roadType: 'Tunnel', duration: 600, status: 'active', description: 'Driving through long tunnels with GPS signal loss', parameters: { tunnelLength: 5000, gpsLoss: true } },
      { name: 'Desert Heat Drive', category: 'Weather', difficulty: 'Medium', weatherCondition: 'Extreme Heat', trafficDensity: 'Low', roadType: 'Highway', duration: 7200, status: 'active', description: 'Long-distance desert driving in extreme heat conditions', parameters: { temperature: 50, mirage: true } },
      { name: 'Multi-Lane Intersection', category: 'Urban', difficulty: 'Hard', weatherCondition: 'Clear', trafficDensity: 'High', roadType: 'Intersection', duration: 300, status: 'active', description: 'Complex multi-lane intersections with turning traffic', parameters: { lanes: 6, signals: true } }
    ]);
    console.log('Driving Scenarios seeded.');

    // Training Sessions (15)
    await TrainingSession.bulkCreate([
      { name: 'Lane Detection v3.2', modelName: 'LaneNet-Pro', algorithm: 'Deep CNN', epochs: 500, learningRate: 0.001, accuracy: 98.5, loss: 0.023, status: 'completed', startedAt: new Date('2024-01-15'), completedAt: new Date('2024-01-18'), description: 'Training lane detection model on diverse road datasets', metrics: { dataset: '500K images', gpu: 'A100' } },
      { name: 'Object Classification v5.0', modelName: 'ObjClassifier-Ultra', algorithm: 'ResNet-152', epochs: 1000, learningRate: 0.0005, accuracy: 97.8, loss: 0.031, status: 'completed', startedAt: new Date('2024-02-01'), completedAt: new Date('2024-02-05'), description: 'Multi-class object classification for road objects', metrics: { classes: 80, dataset: '2M images' } },
      { name: 'Path Planning RL v2.1', modelName: 'PathPlanner-RL', algorithm: 'PPO', epochs: 10000, learningRate: 0.0003, accuracy: 94.2, loss: 0.089, status: 'completed', startedAt: new Date('2024-02-15'), completedAt: new Date('2024-02-22'), description: 'Reinforcement learning for optimal path planning', metrics: { episodes: 1000000, reward: 892 } },
      { name: 'Pedestrian Detection v4.0', modelName: 'PedDetect-Fast', algorithm: 'YOLO-v8', epochs: 300, learningRate: 0.001, accuracy: 99.1, loss: 0.015, status: 'completed', startedAt: new Date('2024-03-01'), completedAt: new Date('2024-03-03'), description: 'Real-time pedestrian detection with high accuracy', metrics: { fps: 60, dataset: '1M images' } },
      { name: 'Traffic Sign Recognition', modelName: 'SignReader-v3', algorithm: 'EfficientNet', epochs: 200, learningRate: 0.001, accuracy: 99.6, loss: 0.008, status: 'completed', startedAt: new Date('2024-03-10'), completedAt: new Date('2024-03-11'), description: 'Traffic sign recognition across 200+ sign types', metrics: { classes: 200, countries: 15 } },
      { name: 'Depth Estimation v2.5', modelName: 'DepthNet-Stereo', algorithm: 'Transformer', epochs: 800, learningRate: 0.0001, accuracy: 96.3, loss: 0.045, status: 'running', startedAt: new Date('2024-03-15'), description: 'Monocular depth estimation from camera images', metrics: { resolution: '1920x1080', progress: '65%' } },
      { name: 'Behavior Prediction v1.8', modelName: 'BehaviorPredict', algorithm: 'LSTM', epochs: 600, learningRate: 0.0005, accuracy: 91.7, loss: 0.102, status: 'completed', startedAt: new Date('2024-03-20'), completedAt: new Date('2024-03-24'), description: 'Predicting other vehicle and pedestrian behavior', metrics: { sequences: 500000, timeHorizon: '5s' } },
      { name: 'Semantic Segmentation v6.0', modelName: 'SegNet-Urban', algorithm: 'DeepLab-v3+', epochs: 400, learningRate: 0.001, accuracy: 97.2, loss: 0.034, status: 'completed', startedAt: new Date('2024-04-01'), completedAt: new Date('2024-04-04'), description: 'Pixel-level semantic segmentation of road scenes', metrics: { classes: 30, mIoU: 0.89 } },
      { name: 'LiDAR Point Cloud v3.0', modelName: 'PointCloud-Pro', algorithm: 'PointNet++', epochs: 700, learningRate: 0.0008, accuracy: 95.8, loss: 0.052, status: 'completed', startedAt: new Date('2024-04-10'), completedAt: new Date('2024-04-15'), description: '3D point cloud processing for LiDAR data', metrics: { points: '100K/frame', fps: 30 } },
      { name: 'Motion Planning GAN', modelName: 'MotionGAN-v2', algorithm: 'GAN', epochs: 2000, learningRate: 0.0002, accuracy: 93.5, loss: 0.078, status: 'completed', startedAt: new Date('2024-04-20'), completedAt: new Date('2024-04-28'), description: 'Generative model for diverse motion planning', metrics: { diversity: 0.92, quality: 0.95 } },
      { name: 'Weather Adaptation v1.2', modelName: 'WeatherAdapt', algorithm: 'Domain Adaptation', epochs: 350, learningRate: 0.001, accuracy: 88.9, loss: 0.134, status: 'running', startedAt: new Date('2024-05-01'), description: 'Adapting perception models for adverse weather', metrics: { conditions: 8, progress: '40%' } },
      { name: 'Multi-Agent RL v1.0', modelName: 'MARL-Traffic', algorithm: 'MAPPO', epochs: 50000, learningRate: 0.0003, accuracy: 89.4, loss: 0.121, status: 'queued', description: 'Multi-agent reinforcement learning for traffic scenarios', metrics: { agents: 50, scenarios: 100 } },
      { name: 'End-to-End Driving v2.0', modelName: 'E2E-Driver', algorithm: 'Imitation Learning', epochs: 1500, learningRate: 0.0001, accuracy: 92.1, loss: 0.095, status: 'completed', startedAt: new Date('2024-05-10'), completedAt: new Date('2024-05-18'), description: 'End-to-end driving from camera to steering', metrics: { hours: 10000, cities: 20 } },
      { name: 'Occupancy Grid v3.5', modelName: 'OccGrid-3D', algorithm: 'Voxel Transformer', epochs: 600, learningRate: 0.0005, accuracy: 96.7, loss: 0.041, status: 'completed', startedAt: new Date('2024-05-20'), completedAt: new Date('2024-05-24'), description: '3D occupancy grid prediction for scene understanding', metrics: { voxelSize: '0.1m', range: '50m' } },
      { name: 'Sensor Fusion v4.2', modelName: 'FusionNet-Multi', algorithm: 'Attention Fusion', epochs: 450, learningRate: 0.0008, accuracy: 98.2, loss: 0.025, status: 'completed', startedAt: new Date('2024-06-01'), completedAt: new Date('2024-06-05'), description: 'Multi-sensor fusion combining LiDAR, camera, and radar', metrics: { sensors: 3, latency: '10ms' } }
    ]);
    console.log('Training Sessions seeded.');

    // Simulation Results (15)
    await SimulationResult.bulkCreate([
      { name: 'Highway Test Run #1247', scenarioName: 'Highway Cruising', vehicleName: 'AutoPilot X1', successRate: 98.5, collisions: 0, nearMisses: 2, avgSpeed: 105.3, totalDistance: 450.2, duration: 15400, grade: 'A+', status: 'completed', description: 'Excellent highway performance with zero collisions' },
      { name: 'Urban Navigation #892', scenarioName: 'Urban Rush Hour', vehicleName: 'CityBot Compact', successRate: 94.2, collisions: 0, nearMisses: 8, avgSpeed: 28.7, totalDistance: 15.3, duration: 1920, grade: 'A', status: 'completed', description: 'Strong urban performance during peak traffic' },
      { name: 'Rain Test #445', scenarioName: 'Rainy Night Drive', vehicleName: 'NightOwl EV', successRate: 91.8, collisions: 1, nearMisses: 5, avgSpeed: 65.2, totalDistance: 43.5, duration: 2400, grade: 'B+', status: 'completed', description: 'Good performance in adverse weather, one minor collision' },
      { name: 'School Zone #201', scenarioName: 'School Zone Navigation', vehicleName: 'SwiftShuttle S2', successRate: 99.8, collisions: 0, nearMisses: 0, avgSpeed: 22.1, totalDistance: 3.7, duration: 605, grade: 'A+', status: 'completed', description: 'Perfect school zone navigation with all pedestrians detected' },
      { name: 'Mountain Drive #78', scenarioName: 'Mountain Pass', vehicleName: 'AutoPilot X1', successRate: 88.5, collisions: 0, nearMisses: 12, avgSpeed: 55.8, totalDistance: 83.7, duration: 5400, grade: 'B', status: 'completed', description: 'Challenging mountain conditions, several near-miss events in fog' },
      { name: 'Parking Test #567', scenarioName: 'Parking Garage', vehicleName: 'ParkPilot EV2', successRate: 96.5, collisions: 0, nearMisses: 1, avgSpeed: 8.5, totalDistance: 0.7, duration: 298, grade: 'A', status: 'completed', description: 'Successful parking in tight garage environment' },
      { name: 'Snow Storm #34', scenarioName: 'Snow Storm Highway', vehicleName: 'FreightMaster 9000', successRate: 82.3, collisions: 2, nearMisses: 15, avgSpeed: 45.2, totalDistance: 45.2, duration: 3600, grade: 'C+', status: 'completed', description: 'Difficult snow storm conditions, multiple incidents recorded' },
      { name: 'Emergency Response #112', scenarioName: 'Emergency Vehicle Response', vehicleName: 'MedEvac One', successRate: 97.2, collisions: 0, nearMisses: 3, avgSpeed: 75.5, totalDistance: 18.9, duration: 900, grade: 'A', status: 'completed', description: 'Effective emergency response with proper yielding behavior' },
      { name: 'Roundabout #223', scenarioName: 'Roundabout Navigation', vehicleName: 'CityBot Compact', successRate: 95.8, collisions: 0, nearMisses: 2, avgSpeed: 30.2, totalDistance: 2.5, duration: 297, grade: 'A', status: 'completed', description: 'Smooth roundabout navigation with proper yielding' },
      { name: 'Highway Merge #890', scenarioName: 'Highway Merge', vehicleName: 'Rally Runner R8', successRate: 93.5, collisions: 0, nearMisses: 4, avgSpeed: 95.8, totalDistance: 3.2, duration: 120, grade: 'A-', status: 'completed', description: 'Aggressive but safe highway merging behavior' },
      { name: 'Construction #445', scenarioName: 'Construction Zone', vehicleName: 'RoboVan Pro', successRate: 96.0, collisions: 0, nearMisses: 2, avgSpeed: 25.3, totalDistance: 8.4, duration: 1200, grade: 'A', status: 'completed', description: 'Safe navigation through construction with worker detection' },
      { name: 'Pedestrian Test #667', scenarioName: 'Pedestrian Crossing', vehicleName: 'BusBot Metro', successRate: 99.5, collisions: 0, nearMisses: 1, avgSpeed: 18.5, totalDistance: 3.1, duration: 600, grade: 'A+', status: 'completed', description: 'Near-perfect pedestrian interaction and yielding' },
      { name: 'Tunnel Drive #189', scenarioName: 'Tunnel Transit', vehicleName: 'AutoPilot X1', successRate: 97.8, collisions: 0, nearMisses: 1, avgSpeed: 88.2, totalDistance: 14.7, duration: 600, grade: 'A', status: 'completed', description: 'Smooth tunnel transit with successful GPS-denied navigation' },
      { name: 'Desert Run #56', scenarioName: 'Desert Heat Drive', vehicleName: 'FreightMaster 9000', successRate: 95.2, collisions: 0, nearMisses: 3, avgSpeed: 110.5, totalDistance: 221.0, duration: 7200, grade: 'A', status: 'completed', description: 'Successful long-distance desert driving despite heat effects' },
      { name: 'Intersection #1001', scenarioName: 'Multi-Lane Intersection', vehicleName: 'CityBot Compact', successRate: 94.8, collisions: 0, nearMisses: 5, avgSpeed: 22.3, totalDistance: 1.9, duration: 300, grade: 'A-', status: 'completed', description: 'Complex intersection navigation with multiple turning vehicles' }
    ]);
    console.log('Simulation Results seeded.');

    // Route Plans (15)
    await RoutePlan.bulkCreate([
      { name: 'Downtown Express', origin: 'Tech Campus HQ', destination: 'Downtown Convention Center', distance: 15.3, estimatedTime: 25, algorithm: 'A* Search', waypoints: 3, optimizationType: 'Fastest', status: 'active', description: 'Optimized route through city center avoiding construction zones' },
      { name: 'Airport Shuttle Route', origin: 'Central Station', destination: 'International Airport', distance: 35.7, estimatedTime: 40, algorithm: 'Dijkstra', waypoints: 5, optimizationType: 'Shortest', status: 'active', description: 'Highway-based route to airport with minimal stops' },
      { name: 'Campus Loop', origin: 'Engineering Building', destination: 'Student Center', distance: 2.1, estimatedTime: 8, algorithm: 'BFS', waypoints: 8, optimizationType: 'Scenic', status: 'active', description: 'Campus circular route covering all major buildings' },
      { name: 'Suburb Commute', origin: 'Residential District A', destination: 'Business Park West', distance: 22.8, estimatedTime: 35, algorithm: 'A* Search', waypoints: 4, optimizationType: 'Balanced', status: 'active', description: 'Suburban commute route balancing speed and fuel efficiency' },
      { name: 'Emergency Route Alpha', origin: 'Fire Station #7', destination: 'City Hospital', distance: 8.5, estimatedTime: 6, algorithm: 'Emergency Routing', waypoints: 0, optimizationType: 'Fastest', status: 'active', description: 'Emergency priority route with traffic light preemption' },
      { name: 'Delivery Circuit #12', origin: 'Distribution Center', destination: 'Shopping Mall Complex', distance: 45.2, estimatedTime: 65, algorithm: 'TSP Solver', waypoints: 12, optimizationType: 'Multi-stop', status: 'active', description: 'Multi-delivery route optimized using traveling salesman approach' },
      { name: 'Coastal Highway', origin: 'Port Authority', destination: 'Beach Resort Area', distance: 78.5, estimatedTime: 55, algorithm: 'Dijkstra', waypoints: 2, optimizationType: 'Scenic', status: 'active', description: 'Scenic coastal highway route with ocean views' },
      { name: 'Industrial Corridor', origin: 'Manufacturing Plant A', destination: 'Logistics Hub B', distance: 18.9, estimatedTime: 30, algorithm: 'A* Search', waypoints: 3, optimizationType: 'Heavy Vehicle', status: 'active', description: 'Route optimized for heavy freight vehicles and truck turns' },
      { name: 'Night Route Omega', origin: 'Night Depot', destination: 'City Center', distance: 12.4, estimatedTime: 15, algorithm: 'Modified A*', waypoints: 1, optimizationType: 'Low Traffic', status: 'active', description: 'Night-optimized route using streets with better lighting' },
      { name: 'School Bus Route #5', origin: 'Bus Depot', destination: 'Lincoln Elementary', distance: 28.3, estimatedTime: 50, algorithm: 'VRP Solver', waypoints: 15, optimizationType: 'Multi-pickup', status: 'active', description: 'School bus route with optimized student pickup sequence' },
      { name: 'Cross-City Express', origin: 'North Terminal', destination: 'South Business District', distance: 32.1, estimatedTime: 45, algorithm: 'Contraction Hierarchies', waypoints: 2, optimizationType: 'Fastest', status: 'active', description: 'Express cross-city route using highways and express lanes' },
      { name: 'Park & Ride Connector', origin: 'Suburban P&R Lot', destination: 'Metro Station', distance: 5.8, estimatedTime: 12, algorithm: 'BFS', waypoints: 3, optimizationType: 'Shortest', status: 'active', description: 'Short connector route from park and ride to transit station' },
      { name: 'Festival Detour', origin: 'Main Entrance', destination: 'Parking Zone F', distance: 4.2, estimatedTime: 20, algorithm: 'A* Search', waypoints: 6, optimizationType: 'Avoid Crowds', status: 'planned', description: 'Detour route during city festival with road closures' },
      { name: 'Highway Loop Test', origin: 'Test Track Start', destination: 'Test Track Start', distance: 95.0, estimatedTime: 60, algorithm: 'Circular Route', waypoints: 0, optimizationType: 'Performance', status: 'active', description: 'Circular highway test route for performance evaluation' },
      { name: 'Medical Transport', origin: 'Clinic Network A', destination: 'Regional Hospital', distance: 14.7, estimatedTime: 20, algorithm: 'Priority Routing', waypoints: 2, optimizationType: 'Smooth Ride', status: 'active', description: 'Medical transport route optimized for patient comfort' }
    ]);
    console.log('Route Plans seeded.');

    // Object Detections (15)
    await ObjectDetection.bulkCreate([
      { name: 'Pedestrian Detector v4', objectType: 'Pedestrian', detectionModel: 'YOLOv8-XL', confidence: 99.2, precision: 98.8, recall: 99.1, f1Score: 98.95, inferenceTime: 12.5, status: 'active', description: 'State-of-the-art pedestrian detection for urban driving' },
      { name: 'Vehicle Classifier Pro', objectType: 'Vehicle', detectionModel: 'EfficientDet-D7', confidence: 98.5, precision: 98.2, recall: 97.9, f1Score: 98.05, inferenceTime: 15.3, status: 'active', description: 'Multi-class vehicle detection and classification' },
      { name: 'Cyclist Tracker', objectType: 'Cyclist', detectionModel: 'CenterNet', confidence: 96.8, precision: 96.2, recall: 95.8, f1Score: 96.0, inferenceTime: 11.8, status: 'active', description: 'Bicycle and motorcycle rider detection with trajectory prediction' },
      { name: 'Traffic Sign Reader', objectType: 'Traffic Sign', detectionModel: 'FCOS', confidence: 99.5, precision: 99.3, recall: 99.2, f1Score: 99.25, inferenceTime: 8.2, status: 'active', description: 'High-accuracy traffic sign detection and classification' },
      { name: 'Traffic Light Detector', objectType: 'Traffic Light', detectionModel: 'SSD-MobileNet', confidence: 98.9, precision: 98.5, recall: 98.7, f1Score: 98.6, inferenceTime: 6.5, status: 'active', description: 'Traffic light state detection including arrow signals' },
      { name: 'Lane Marker Detector', objectType: 'Lane Marking', detectionModel: 'LaneNet-v3', confidence: 97.5, precision: 97.0, recall: 96.8, f1Score: 96.9, inferenceTime: 10.1, status: 'active', description: 'Lane line and road marking detection system' },
      { name: 'Construction Cone Finder', objectType: 'Construction Object', detectionModel: 'YOLOv8-S', confidence: 97.2, precision: 96.8, recall: 97.0, f1Score: 96.9, inferenceTime: 7.8, status: 'active', description: 'Detection of cones, barriers, and construction equipment' },
      { name: 'Animal Detector', objectType: 'Animal', detectionModel: 'Faster R-CNN', confidence: 94.5, precision: 93.8, recall: 94.2, f1Score: 94.0, inferenceTime: 18.5, status: 'active', description: 'Wildlife and domestic animal detection on roadways' },
      { name: 'Road Obstacle Scanner', objectType: 'Road Obstacle', detectionModel: 'PointPillars', confidence: 95.8, precision: 95.2, recall: 95.5, f1Score: 95.35, inferenceTime: 14.2, status: 'active', description: '3D obstacle detection using LiDAR point clouds' },
      { name: 'Emergency Vehicle ID', objectType: 'Emergency Vehicle', detectionModel: 'YOLOv8-M', confidence: 98.2, precision: 97.8, recall: 98.0, f1Score: 97.9, inferenceTime: 9.8, status: 'active', description: 'Detection and classification of emergency vehicles with sirens' },
      { name: 'Pothole Detector', objectType: 'Road Defect', detectionModel: 'U-Net', confidence: 92.3, precision: 91.5, recall: 92.0, f1Score: 91.75, inferenceTime: 16.2, status: 'active', description: 'Road surface defect and pothole detection' },
      { name: 'Crosswalk Detector', objectType: 'Crosswalk', detectionModel: 'Mask R-CNN', confidence: 97.8, precision: 97.5, recall: 97.2, f1Score: 97.35, inferenceTime: 13.5, status: 'active', description: 'Crosswalk and pedestrian crossing zone detection' },
      { name: 'Speed Bump Finder', objectType: 'Speed Bump', detectionModel: 'RetinaNet', confidence: 96.0, precision: 95.5, recall: 95.8, f1Score: 95.65, inferenceTime: 9.2, status: 'active', description: 'Speed bump and road hump detection for ride comfort' },
      { name: 'Debris Scanner', objectType: 'Road Debris', detectionModel: 'YOLOv8-L', confidence: 93.8, precision: 93.2, recall: 93.5, f1Score: 93.35, inferenceTime: 11.5, status: 'active', description: 'Detection of road debris, fallen objects, and tire remnants' },
      { name: 'Parking Space Locator', objectType: 'Parking Space', detectionModel: 'Custom CNN', confidence: 97.0, precision: 96.5, recall: 96.8, f1Score: 96.65, inferenceTime: 8.8, status: 'active', description: 'Available parking space detection using camera and ultrasonic data' }
    ]);
    console.log('Object Detections seeded.');

    // Traffic Simulations (15)
    await TrafficSimulation.bulkCreate([
      { name: 'Morning Rush Downtown', scenarioType: 'Rush Hour', vehicleCount: 2500, pedestrianCount: 800, avgFlowRate: 1200, congestionLevel: 'High', intersections: 25, duration: 3600, status: 'active', description: 'Peak morning traffic in downtown area' },
      { name: 'Highway I-95 Flow', scenarioType: 'Highway', vehicleCount: 5000, pedestrianCount: 0, avgFlowRate: 3500, congestionLevel: 'Medium', intersections: 0, duration: 7200, status: 'active', description: 'Interstate highway traffic flow simulation' },
      { name: 'Suburban Evening', scenarioType: 'Residential', vehicleCount: 800, pedestrianCount: 300, avgFlowRate: 600, congestionLevel: 'Low', intersections: 15, duration: 3600, status: 'active', description: 'Evening residential area traffic pattern' },
      { name: 'Stadium Event Exit', scenarioType: 'Event', vehicleCount: 15000, pedestrianCount: 50000, avgFlowRate: 500, congestionLevel: 'Extreme', intersections: 8, duration: 5400, status: 'active', description: 'Post-game stadium traffic dispersal simulation' },
      { name: 'School Zone AM', scenarioType: 'School Zone', vehicleCount: 400, pedestrianCount: 500, avgFlowRate: 200, congestionLevel: 'Medium', intersections: 4, duration: 1800, status: 'active', description: 'Morning school drop-off traffic pattern' },
      { name: 'Emergency Corridor', scenarioType: 'Emergency', vehicleCount: 1500, pedestrianCount: 200, avgFlowRate: 800, congestionLevel: 'High', intersections: 10, duration: 900, status: 'active', description: 'Traffic clearing for emergency vehicle corridor' },
      { name: 'Night Traffic Flow', scenarioType: 'Night', vehicleCount: 300, pedestrianCount: 50, avgFlowRate: 250, congestionLevel: 'Very Low', intersections: 20, duration: 7200, status: 'active', description: 'Late night minimal traffic simulation' },
      { name: 'Construction Detour', scenarioType: 'Construction', vehicleCount: 1800, pedestrianCount: 100, avgFlowRate: 400, congestionLevel: 'High', intersections: 12, duration: 3600, status: 'active', description: 'Traffic rerouting due to road construction' },
      { name: 'Freeway Accident', scenarioType: 'Incident', vehicleCount: 4000, pedestrianCount: 0, avgFlowRate: 200, congestionLevel: 'Extreme', intersections: 0, duration: 5400, status: 'active', description: 'Freeway traffic impact from multi-vehicle accident' },
      { name: 'Shopping District', scenarioType: 'Commercial', vehicleCount: 1200, pedestrianCount: 2000, avgFlowRate: 800, congestionLevel: 'Medium', intersections: 8, duration: 3600, status: 'active', description: 'Weekend shopping district traffic and pedestrian activity' },
      { name: 'Rain Reduced Capacity', scenarioType: 'Weather Impact', vehicleCount: 2000, pedestrianCount: 100, avgFlowRate: 900, congestionLevel: 'High', intersections: 20, duration: 3600, status: 'active', description: 'Traffic flow reduction due to rainy conditions' },
      { name: 'Multi-Modal Transit Hub', scenarioType: 'Transit', vehicleCount: 1000, pedestrianCount: 5000, avgFlowRate: 700, congestionLevel: 'Medium', intersections: 6, duration: 3600, status: 'active', description: 'Bus, rail, and vehicle traffic at transit hub' },
      { name: 'Holiday Weekend', scenarioType: 'Holiday', vehicleCount: 8000, pedestrianCount: 500, avgFlowRate: 1500, congestionLevel: 'Very High', intersections: 30, duration: 14400, status: 'active', description: 'Extended holiday weekend traffic patterns' },
      { name: 'Parking Lot Flow', scenarioType: 'Parking', vehicleCount: 500, pedestrianCount: 400, avgFlowRate: 100, congestionLevel: 'Low', intersections: 0, duration: 3600, status: 'active', description: 'Shopping center parking lot vehicle and pedestrian flow' },
      { name: 'Smart Signal Optimization', scenarioType: 'Smart City', vehicleCount: 3000, pedestrianCount: 1000, avgFlowRate: 2200, congestionLevel: 'Low', intersections: 20, duration: 3600, status: 'active', description: 'AI-optimized traffic signal timing simulation' }
    ]);
    console.log('Traffic Simulations seeded.');

    // Weather Simulations (15)
    await WeatherSimulation.bulkCreate([
      { name: 'Clear Sunny Day', weatherType: 'Clear', intensity: 'None', visibility: 10000, windSpeed: 5, precipitation: 0, temperature: 25, roadCondition: 'Dry', status: 'active', description: 'Ideal driving conditions with clear visibility' },
      { name: 'Light Rain Shower', weatherType: 'Rain', intensity: 'Light', visibility: 5000, windSpeed: 15, precipitation: 5, temperature: 18, roadCondition: 'Wet', status: 'active', description: 'Light rain with slightly reduced visibility' },
      { name: 'Heavy Thunderstorm', weatherType: 'Thunderstorm', intensity: 'Heavy', visibility: 500, windSpeed: 60, precipitation: 50, temperature: 22, roadCondition: 'Flooded', status: 'active', description: 'Severe thunderstorm with heavy rain and wind' },
      { name: 'Dense Fog', weatherType: 'Fog', intensity: 'Heavy', visibility: 100, windSpeed: 2, precipitation: 0, temperature: 8, roadCondition: 'Damp', status: 'active', description: 'Dense fog conditions with near-zero visibility' },
      { name: 'Light Snow', weatherType: 'Snow', intensity: 'Light', visibility: 3000, windSpeed: 10, precipitation: 8, temperature: -2, roadCondition: 'Snowy', status: 'active', description: 'Light snowfall with moderate visibility' },
      { name: 'Blizzard Conditions', weatherType: 'Blizzard', intensity: 'Extreme', visibility: 50, windSpeed: 80, precipitation: 40, temperature: -15, roadCondition: 'Ice', status: 'active', description: 'Whiteout blizzard with extreme wind and ice' },
      { name: 'Freezing Rain', weatherType: 'Ice Storm', intensity: 'Moderate', visibility: 2000, windSpeed: 20, precipitation: 15, temperature: -1, roadCondition: 'Black Ice', status: 'active', description: 'Freezing rain creating dangerous black ice conditions' },
      { name: 'Desert Sandstorm', weatherType: 'Sandstorm', intensity: 'Heavy', visibility: 200, windSpeed: 70, precipitation: 0, temperature: 42, roadCondition: 'Sandy', status: 'active', description: 'Desert sandstorm with severely reduced visibility' },
      { name: 'Tropical Downpour', weatherType: 'Tropical Rain', intensity: 'Heavy', visibility: 800, windSpeed: 45, precipitation: 80, temperature: 30, roadCondition: 'Flooded', status: 'active', description: 'Tropical monsoon rain with road flooding' },
      { name: 'Morning Mist', weatherType: 'Mist', intensity: 'Light', visibility: 2000, windSpeed: 3, precipitation: 0, temperature: 12, roadCondition: 'Damp', status: 'active', description: 'Early morning mist with gradually improving conditions' },
      { name: 'Hailstorm', weatherType: 'Hail', intensity: 'Moderate', visibility: 3000, windSpeed: 35, precipitation: 20, temperature: 5, roadCondition: 'Wet', status: 'active', description: 'Hailstorm with moderate-sized hailstones' },
      { name: 'Extreme Heat Wave', weatherType: 'Extreme Heat', intensity: 'Heavy', visibility: 8000, windSpeed: 8, precipitation: 0, temperature: 48, roadCondition: 'Soft Asphalt', status: 'active', description: 'Extreme heat causing road surface degradation and mirages' },
      { name: 'Gusty Crosswinds', weatherType: 'Wind', intensity: 'Heavy', visibility: 8000, windSpeed: 90, precipitation: 0, temperature: 15, roadCondition: 'Dry', status: 'active', description: 'Strong crosswinds affecting vehicle stability' },
      { name: 'Sleet Mix', weatherType: 'Sleet', intensity: 'Moderate', visibility: 1500, windSpeed: 25, precipitation: 12, temperature: 0, roadCondition: 'Slushy', status: 'active', description: 'Mixed sleet and rain creating slushy road conditions' },
      { name: 'Post-Storm Wet', weatherType: 'Post-Storm', intensity: 'Light', visibility: 6000, windSpeed: 12, precipitation: 2, temperature: 16, roadCondition: 'Wet with Puddles', status: 'active', description: 'Post-storm conditions with standing water and debris' }
    ]);
    console.log('Weather Simulations seeded.');

    // Safety Metrics (15)
    await SafetyMetric.bulkCreate([
      { name: 'Collision Avoidance Rate', category: 'Collision Prevention', score: 98.7, maxScore: 100, testCount: 10000, passRate: 99.2, riskLevel: 'Low', standard: 'ISO 26262', status: 'active', description: 'Percentage of potential collisions successfully avoided' },
      { name: 'Pedestrian Safety Score', category: 'Pedestrian Protection', score: 99.5, maxScore: 100, testCount: 5000, passRate: 99.8, riskLevel: 'Very Low', standard: 'Euro NCAP', status: 'active', description: 'Safety rating for pedestrian interaction scenarios' },
      { name: 'Emergency Braking Performance', category: 'Braking Systems', score: 97.3, maxScore: 100, testCount: 8000, passRate: 98.1, riskLevel: 'Low', standard: 'FMVSS 135', status: 'active', description: 'Autonomous emergency braking system effectiveness' },
      { name: 'Lane Keeping Accuracy', category: 'Lane Assistance', score: 96.8, maxScore: 100, testCount: 15000, passRate: 97.5, riskLevel: 'Low', standard: 'SAE J3016', status: 'active', description: 'Accuracy of lane keeping assistance system' },
      { name: 'Sensor Redundancy Score', category: 'System Reliability', score: 94.5, maxScore: 100, testCount: 3000, passRate: 96.0, riskLevel: 'Medium', standard: 'ISO 26262 ASIL-D', status: 'active', description: 'Sensor system redundancy and failover capability' },
      { name: 'Night Driving Safety', category: 'Visibility', score: 92.1, maxScore: 100, testCount: 6000, passRate: 94.5, riskLevel: 'Medium', standard: 'UNECE R48', status: 'active', description: 'Overall safety performance during nighttime driving' },
      { name: 'Weather Resilience Index', category: 'Environmental', score: 88.5, maxScore: 100, testCount: 4000, passRate: 91.2, riskLevel: 'Medium', standard: 'SAE J3016', status: 'active', description: 'System performance across various weather conditions' },
      { name: 'Cyber Security Rating', category: 'Cybersecurity', score: 95.8, maxScore: 100, testCount: 2000, passRate: 97.0, riskLevel: 'Low', standard: 'ISO/SAE 21434', status: 'active', description: 'Vehicle cybersecurity and intrusion prevention rating' },
      { name: 'Functional Safety Level', category: 'Functional Safety', score: 97.0, maxScore: 100, testCount: 5000, passRate: 98.5, riskLevel: 'Low', standard: 'ISO 26262 ASIL-B', status: 'active', description: 'Overall functional safety assessment score' },
      { name: 'V2X Communication Score', category: 'Connectivity', score: 91.3, maxScore: 100, testCount: 3500, passRate: 93.8, riskLevel: 'Medium', standard: 'IEEE 802.11p', status: 'active', description: 'Vehicle-to-everything communication reliability' },
      { name: 'Failsafe Response Time', category: 'System Recovery', score: 96.5, maxScore: 100, testCount: 7000, passRate: 97.8, riskLevel: 'Low', standard: 'ISO 26262', status: 'active', description: 'System failsafe activation and response time' },
      { name: 'ODD Compliance', category: 'Operational Domain', score: 93.2, maxScore: 100, testCount: 4500, passRate: 95.0, riskLevel: 'Medium', standard: 'SAE J3016', status: 'active', description: 'Operational Design Domain boundary detection compliance' },
      { name: 'Human Handoff Safety', category: 'Transition Safety', score: 89.8, maxScore: 100, testCount: 2500, passRate: 92.5, riskLevel: 'Medium', standard: 'NHTSA AV Policy', status: 'active', description: 'Safety of autonomous-to-manual driving transition' },
      { name: 'Road User Interaction', category: 'Social Driving', score: 94.0, maxScore: 100, testCount: 6000, passRate: 96.2, riskLevel: 'Low', standard: 'Euro NCAP', status: 'active', description: 'Safe interaction with other road users and vulnerable groups' },
      { name: 'System Uptime Reliability', category: 'Availability', score: 99.9, maxScore: 100, testCount: 10000, passRate: 99.95, riskLevel: 'Very Low', standard: 'ISO 26262 ASIL-D', status: 'active', description: 'System availability and uptime performance metric' }
    ]);
    console.log('Safety Metrics seeded.');

    // Fleet Vehicles (15)
    await FleetVehicle.bulkCreate([
      { name: 'Alpha-001', vehicleId: 'AV-2024-001', model: 'AutoPilot X1', location: 'San Francisco, CA', mileage: 45230, batteryLevel: 87, lastMaintenance: new Date('2024-05-15'), nextMaintenance: new Date('2024-08-15'), operationalStatus: 'operational', status: 'active', description: 'Primary test vehicle for urban scenarios' },
      { name: 'Beta-002', vehicleId: 'AV-2024-002', model: 'CityBot Compact', location: 'Austin, TX', mileage: 32100, batteryLevel: 92, lastMaintenance: new Date('2024-06-01'), nextMaintenance: new Date('2024-09-01'), operationalStatus: 'operational', status: 'active', description: 'City driving test vehicle' },
      { name: 'Gamma-003', vehicleId: 'AV-2024-003', model: 'FreightMaster 9000', location: 'Phoenix, AZ', mileage: 128500, batteryLevel: 65, lastMaintenance: new Date('2024-04-20'), nextMaintenance: new Date('2024-07-20'), operationalStatus: 'maintenance', status: 'active', description: 'Long-haul freight test truck' },
      { name: 'Delta-004', vehicleId: 'AV-2024-004', model: 'SwiftShuttle S2', location: 'Miami, FL', mileage: 18700, batteryLevel: 95, lastMaintenance: new Date('2024-06-10'), nextMaintenance: new Date('2024-09-10'), operationalStatus: 'operational', status: 'active', description: 'Airport shuttle test vehicle' },
      { name: 'Epsilon-005', vehicleId: 'AV-2024-005', model: 'NightOwl EV', location: 'Seattle, WA', mileage: 27800, batteryLevel: 78, lastMaintenance: new Date('2024-05-25'), nextMaintenance: new Date('2024-08-25'), operationalStatus: 'operational', status: 'active', description: 'Night driving test vehicle' },
      { name: 'Zeta-006', vehicleId: 'AV-2024-006', model: 'RoboVan Pro', location: 'Denver, CO', mileage: 56200, batteryLevel: 45, lastMaintenance: new Date('2024-03-15'), nextMaintenance: new Date('2024-06-15'), operationalStatus: 'charging', status: 'active', description: 'Delivery van test vehicle' },
      { name: 'Eta-007', vehicleId: 'AV-2024-007', model: 'BusBot Metro', location: 'Portland, OR', mileage: 89300, batteryLevel: 72, lastMaintenance: new Date('2024-05-01'), nextMaintenance: new Date('2024-08-01'), operationalStatus: 'operational', status: 'active', description: 'Public transit bus test vehicle' },
      { name: 'Theta-008', vehicleId: 'AV-2024-008', model: 'MedEvac One', location: 'Chicago, IL', mileage: 15600, batteryLevel: 98, lastMaintenance: new Date('2024-06-15'), nextMaintenance: new Date('2024-09-15'), operationalStatus: 'standby', status: 'active', description: 'Emergency medical transport test vehicle' },
      { name: 'Iota-009', vehicleId: 'AV-2024-009', model: 'Rally Runner R8', location: 'Las Vegas, NV', mileage: 8900, batteryLevel: 88, lastMaintenance: new Date('2024-06-05'), nextMaintenance: new Date('2024-09-05'), operationalStatus: 'operational', status: 'active', description: 'High-performance test vehicle' },
      { name: 'Kappa-010', vehicleId: 'AV-2024-010', model: 'MicroPod Alpha', location: 'San Jose, CA', mileage: 12400, batteryLevel: 91, lastMaintenance: new Date('2024-06-08'), nextMaintenance: new Date('2024-09-08'), operationalStatus: 'operational', status: 'active', description: 'Last-mile transport pod test vehicle' },
      { name: 'Lambda-011', vehicleId: 'AV-2024-011', model: 'AutoPilot X1', location: 'Boston, MA', mileage: 38700, batteryLevel: 55, lastMaintenance: new Date('2024-04-10'), nextMaintenance: new Date('2024-07-10'), operationalStatus: 'charging', status: 'active', description: 'East coast urban test vehicle' },
      { name: 'Mu-012', vehicleId: 'AV-2024-012', model: 'AgroDrive T4', location: 'Des Moines, IA', mileage: 5600, batteryLevel: 82, lastMaintenance: new Date('2024-05-20'), nextMaintenance: new Date('2024-08-20'), operationalStatus: 'operational', status: 'active', description: 'Agricultural autonomous test vehicle' },
      { name: 'Nu-013', vehicleId: 'AV-2024-013', model: 'ParkPilot EV2', location: 'Atlanta, GA', mileage: 21300, batteryLevel: 76, lastMaintenance: new Date('2024-05-30'), nextMaintenance: new Date('2024-08-30'), operationalStatus: 'operational', status: 'active', description: 'Parking system test vehicle' },
      { name: 'Xi-014', vehicleId: 'AV-2024-014', model: 'CoastGuard Marine', location: 'San Diego, CA', mileage: 3200, batteryLevel: 90, lastMaintenance: new Date('2024-06-12'), nextMaintenance: new Date('2024-09-12'), operationalStatus: 'docked', status: 'active', description: 'Marine autonomous test vessel' },
      { name: 'Omicron-015', vehicleId: 'AV-2024-015', model: 'SkyCab Drone', location: 'Dallas, TX', mileage: 1800, batteryLevel: 100, lastMaintenance: new Date('2024-06-18'), nextMaintenance: new Date('2024-09-18'), operationalStatus: 'grounded', status: 'testing', description: 'VTOL air taxi test vehicle' }
    ]);
    console.log('Fleet Vehicles seeded.');

    // Map Environments (15)
    await MapEnvironment.bulkCreate([
      { name: 'San Francisco Downtown', environmentType: 'Urban', size: 25.5, complexity: 'High', laneCount: 4, hasIntersections: true, hasPedestrians: true, region: 'West Coast USA', status: 'active', description: 'Detailed recreation of SF downtown with hills and cable car tracks' },
      { name: 'German Autobahn A9', environmentType: 'Highway', size: 150.0, complexity: 'Medium', laneCount: 6, hasIntersections: false, hasPedestrians: false, region: 'Germany', status: 'active', description: 'High-speed autobahn segment with no speed limit zones' },
      { name: 'Tokyo Shibuya District', environmentType: 'Dense Urban', size: 8.0, complexity: 'Very High', laneCount: 6, hasIntersections: true, hasPedestrians: true, region: 'Japan', status: 'active', description: 'Extremely dense urban environment with complex pedestrian flows' },
      { name: 'Arizona Desert Highway', environmentType: 'Desert', size: 200.0, complexity: 'Low', laneCount: 4, hasIntersections: false, hasPedestrians: false, region: 'Southwest USA', status: 'active', description: 'Long desert highway for endurance and heat testing' },
      { name: 'London City Center', environmentType: 'Urban', size: 30.0, complexity: 'High', laneCount: 4, hasIntersections: true, hasPedestrians: true, region: 'UK', status: 'active', description: 'Complex London streets with left-hand traffic and roundabouts' },
      { name: 'Mountain Pass Colorado', environmentType: 'Mountain', size: 85.0, complexity: 'High', laneCount: 2, hasIntersections: false, hasPedestrians: false, region: 'Mountain USA', status: 'active', description: 'Steep mountain passes with hairpin turns and elevation changes' },
      { name: 'Suburban Residential', environmentType: 'Suburban', size: 45.0, complexity: 'Medium', laneCount: 2, hasIntersections: true, hasPedestrians: true, region: 'Midwest USA', status: 'active', description: 'Typical American suburban neighborhood with cul-de-sacs' },
      { name: 'Industrial Port Area', environmentType: 'Industrial', size: 12.0, complexity: 'Medium', laneCount: 2, hasIntersections: true, hasPedestrians: false, region: 'East Coast USA', status: 'active', description: 'Port and warehouse district with heavy vehicle traffic' },
      { name: 'University Campus', environmentType: 'Campus', size: 5.0, complexity: 'Medium', laneCount: 2, hasIntersections: true, hasPedestrians: true, region: 'California', status: 'active', description: 'University campus with mixed pedestrian and vehicle zones' },
      { name: 'Singapore Smart City', environmentType: 'Smart City', size: 20.0, complexity: 'High', laneCount: 4, hasIntersections: true, hasPedestrians: true, region: 'Southeast Asia', status: 'active', description: 'Smart city environment with V2X infrastructure' },
      { name: 'Nordic Winter Roads', environmentType: 'Winter', size: 100.0, complexity: 'High', laneCount: 2, hasIntersections: true, hasPedestrians: false, region: 'Scandinavia', status: 'active', description: 'Snow-covered Nordic roads with limited daylight' },
      { name: 'Mumbai Traffic Chaos', environmentType: 'Chaotic Urban', size: 15.0, complexity: 'Extreme', laneCount: 6, hasIntersections: true, hasPedestrians: true, region: 'India', status: 'active', description: 'Highly unpredictable traffic with mixed vehicle types' },
      { name: 'Airport Terminal Loop', environmentType: 'Airport', size: 8.0, complexity: 'Medium', laneCount: 3, hasIntersections: true, hasPedestrians: true, region: 'International', status: 'active', description: 'Airport terminal pickup and dropoff loop' },
      { name: 'Rural Farmland', environmentType: 'Rural', size: 500.0, complexity: 'Low', laneCount: 2, hasIntersections: false, hasPedestrians: false, region: 'Central USA', status: 'active', description: 'Open farmland roads for agricultural vehicle testing' },
      { name: 'Rainy Tropical City', environmentType: 'Tropical Urban', size: 18.0, complexity: 'High', laneCount: 4, hasIntersections: true, hasPedestrians: true, region: 'Southeast Asia', status: 'active', description: 'Tropical city with frequent rain and flooding areas' }
    ]);
    console.log('Map Environments seeded.');

    // AI Models (15)
    await AIModel.bulkCreate([
      { name: 'PerceptionNet v5.2', version: '5.2.0', framework: 'PyTorch', architecture: 'Transformer + CNN', parameters: '450M', accuracy: 98.2, inferenceSpeed: 15.3, trainedOn: 'nuScenes + Waymo Open', status: 'production', description: 'Primary perception model for multi-modal sensor fusion' },
      { name: 'PlannerGPT v3.0', version: '3.0.1', framework: 'PyTorch', architecture: 'GPT-based Planner', parameters: '1.2B', accuracy: 96.5, inferenceSpeed: 25.0, trainedOn: 'Custom Planning Dataset', status: 'production', description: 'Language-model based motion planning system' },
      { name: 'DetectFormer v4.1', version: '4.1.0', framework: 'PyTorch', architecture: 'DETR Variant', parameters: '280M', accuracy: 97.8, inferenceSpeed: 12.0, trainedOn: 'COCO + Custom AV', status: 'production', description: 'Transformer-based 3D object detection' },
      { name: 'LaneTracker v2.8', version: '2.8.3', framework: 'TensorFlow', architecture: 'U-Net + LSTM', parameters: '85M', accuracy: 99.1, inferenceSpeed: 8.5, trainedOn: 'TuSimple + CULane', status: 'production', description: 'Real-time lane detection and tracking' },
      { name: 'BehaviorPredictor v1.5', version: '1.5.0', framework: 'JAX', architecture: 'Graph Neural Network', parameters: '320M', accuracy: 91.2, inferenceSpeed: 20.0, trainedOn: 'Argoverse 2', status: 'testing', description: 'Multi-agent behavior prediction model' },
      { name: 'DepthMaster v3.3', version: '3.3.0', framework: 'PyTorch', architecture: 'Vision Transformer', parameters: '200M', accuracy: 96.0, inferenceSpeed: 18.0, trainedOn: 'KITTI + DrivingStereo', status: 'production', description: 'Monocular depth estimation with metric accuracy' },
      { name: 'SignClassifier v6.0', version: '6.0.2', framework: 'TensorFlow Lite', architecture: 'MobileNet-v4', parameters: '12M', accuracy: 99.5, inferenceSpeed: 3.2, trainedOn: 'GTSRB + MTSD', status: 'production', description: 'Lightweight traffic sign classifier for edge deployment' },
      { name: 'OccupancyNet v2.0', version: '2.0.0', framework: 'PyTorch', architecture: '3D Voxel Transformer', parameters: '500M', accuracy: 94.8, inferenceSpeed: 30.0, trainedOn: 'nuScenes Occupancy', status: 'testing', description: '3D occupancy prediction for scene understanding' },
      { name: 'WeatherAdaptNet v1.3', version: '1.3.0', framework: 'PyTorch', architecture: 'Domain Adaptation CNN', parameters: '150M', accuracy: 89.5, inferenceSpeed: 14.0, trainedOn: 'Multi-Weather Dataset', status: 'testing', description: 'Weather-adaptive perception enhancement' },
      { name: 'FusionEngine v4.0', version: '4.0.0', framework: 'C++ / TensorRT', architecture: 'Multi-Head Attention', parameters: '380M', accuracy: 98.5, inferenceSpeed: 10.0, trainedOn: 'Custom Multi-Sensor', status: 'production', description: 'High-performance multi-sensor fusion engine' },
      { name: 'ParkingAI v2.5', version: '2.5.1', framework: 'PyTorch', architecture: 'Spatial CNN', parameters: '45M', accuracy: 97.0, inferenceSpeed: 6.0, trainedOn: 'Parking Dataset v3', status: 'production', description: 'Autonomous parking spot detection and path planning' },
      { name: 'EmergencyNet v1.0', version: '1.0.0', framework: 'TensorFlow', architecture: 'ResNet + Attention', parameters: '95M', accuracy: 98.8, inferenceSpeed: 5.5, trainedOn: 'Emergency Vehicle DB', status: 'production', description: 'Emergency vehicle and siren detection' },
      { name: 'MapBuilder v3.1', version: '3.1.0', framework: 'PyTorch', architecture: 'BEV Transformer', parameters: '420M', accuracy: 95.5, inferenceSpeed: 22.0, trainedOn: 'HD Map Dataset', status: 'production', description: 'Real-time HD map construction from sensor data' },
      { name: 'SimWorld v1.8', version: '1.8.0', framework: 'Unity ML', architecture: 'World Model GAN', parameters: '2.1B', accuracy: 92.0, inferenceSpeed: 45.0, trainedOn: 'Driving Video Dataset', status: 'research', description: 'Generative world model for simulation environments' },
      { name: 'SafetyGuard v2.2', version: '2.2.0', framework: 'PyTorch', architecture: 'Ensemble + Rules', parameters: '250M', accuracy: 99.8, inferenceSpeed: 4.0, trainedOn: 'Safety Critical DB', status: 'production', description: 'Safety monitoring and intervention system' }
    ]);
    console.log('AI Models seeded.');

    // Collision Analyses (15)
    await CollisionAnalysis.bulkCreate([
      { name: 'Rear-End Highway #1247', collisionType: 'Rear-End', severity: 'Minor', speed: 45.0, cause: 'Sudden braking by lead vehicle', avoidable: true, vehicleInvolved: 'AutoPilot X1', location: 'Highway I-280 Mile 42', recommendations: 'Increase following distance parameter by 15%', status: 'analyzed', description: 'Minor rear-end contact during highway following' },
      { name: 'Pedestrian Near-Miss #892', collisionType: 'Pedestrian', severity: 'Critical', speed: 30.0, cause: 'Jaywalking pedestrian behind parked car', avoidable: true, vehicleInvolved: 'CityBot Compact', location: 'Market Street, SF', recommendations: 'Enhance occluded pedestrian prediction model', status: 'analyzed', description: 'Near-miss with jaywalking pedestrian emerging from occlusion' },
      { name: 'Side-Swipe Merge #445', collisionType: 'Side-Swipe', severity: 'Moderate', speed: 85.0, cause: 'Blind spot during lane merge', avoidable: true, vehicleInvolved: 'Rally Runner R8', location: 'Highway 101 On-ramp', recommendations: 'Add redundant side radar check during merge maneuver', status: 'analyzed', description: 'Side contact during aggressive highway merge' },
      { name: 'Intersection T-Bone #334', collisionType: 'T-Bone', severity: 'Severe', speed: 55.0, cause: 'Red-light runner from cross traffic', avoidable: false, vehicleInvolved: 'BusBot Metro', location: '5th & Mission, SF', recommendations: 'Implement intersection scanning even on green light', status: 'analyzed', description: 'T-bone collision from red-light running vehicle' },
      { name: 'Parking Lot Scrape #201', collisionType: 'Low-Speed Contact', severity: 'Minor', speed: 5.0, cause: 'Tight parking space miscalculation', avoidable: true, vehicleInvolved: 'ParkPilot EV2', location: 'Mall Parking Garage B3', recommendations: 'Reduce minimum clearance threshold from 15cm to 20cm', status: 'analyzed', description: 'Minor scrape during automated parking in tight space' },
      { name: 'Cyclist Conflict #567', collisionType: 'Cyclist', severity: 'Moderate', speed: 25.0, cause: 'Cyclist swerved into vehicle path', avoidable: true, vehicleInvolved: 'AutoPilot X1', location: 'Embarcadero, SF', recommendations: 'Increase lateral buffer zone for cyclists to 1.5m', status: 'analyzed', description: 'Contact with swerving cyclist on shared road' },
      { name: 'Weather-Related Slide #78', collisionType: 'Single Vehicle', severity: 'Moderate', speed: 60.0, cause: 'Black ice causing loss of traction', avoidable: true, vehicleInvolved: 'FreightMaster 9000', location: 'Mountain Pass Route 50', recommendations: 'Integrate real-time road surface temperature data', status: 'analyzed', description: 'Vehicle slide on black ice during mountain driving' },
      { name: 'Construction Zone #112', collisionType: 'Fixed Object', severity: 'Minor', speed: 15.0, cause: 'Undetected construction barrel', avoidable: true, vehicleInvolved: 'RoboVan Pro', location: 'Highway 280 Construction', recommendations: 'Update construction object detection training data', status: 'analyzed', description: 'Contact with construction barrel in work zone' },
      { name: 'Animal Crossing #89', collisionType: 'Animal', severity: 'Minor', speed: 70.0, cause: 'Deer crossing highway at night', avoidable: false, vehicleInvolved: 'NightOwl EV', location: 'Rural Route 35', recommendations: 'Enhance thermal camera animal detection range', status: 'analyzed', description: 'Collision with deer crossing highway at night' },
      { name: 'Multi-Vehicle Chain #23', collisionType: 'Multi-Vehicle', severity: 'Severe', speed: 90.0, cause: 'Chain reaction from sudden stop', avoidable: false, vehicleInvolved: 'AutoPilot X1', location: 'Interstate 5', recommendations: 'Implement V2V communication for chain reaction prevention', status: 'analyzed', description: 'Involvement in multi-vehicle chain reaction collision' },
      { name: 'Roundabout Entry #156', collisionType: 'Side-Impact', severity: 'Minor', speed: 20.0, cause: 'Misjudged gap in roundabout traffic', avoidable: true, vehicleInvolved: 'CityBot Compact', location: 'Columbus Circle', recommendations: 'Recalibrate gap acceptance model for roundabouts', status: 'analyzed', description: 'Side impact during roundabout entry with insufficient gap' },
      { name: 'Door Zone Cyclist #234', collisionType: 'Door Zone', severity: 'Moderate', speed: 18.0, cause: 'Parked car door opened into path', avoidable: true, vehicleInvolved: 'SwiftShuttle S2', location: 'Valencia St, SF', recommendations: 'Add door opening prediction from interior vehicle monitoring', status: 'analyzed', description: 'Conflict caused by suddenly opened parked car door' },
      { name: 'Tunnel Wall Brush #67', collisionType: 'Fixed Object', severity: 'Minor', speed: 55.0, cause: 'GPS signal loss in tunnel', avoidable: true, vehicleInvolved: 'FreightMaster 9000', location: 'Caldecott Tunnel', recommendations: 'Improve IMU-based dead reckoning in GPS-denied areas', status: 'analyzed', description: 'Minor wall contact during tunnel transit with GPS loss' },
      { name: 'Emergency Brake Fail #12', collisionType: 'Rear-End', severity: 'Moderate', speed: 40.0, cause: 'Wet road extended braking distance', avoidable: true, vehicleInvolved: 'BusBot Metro', location: 'Geary Blvd, SF', recommendations: 'Dynamically adjust braking models based on road surface moisture', status: 'analyzed', description: 'Rear-end collision due to extended braking distance on wet road' },
      { name: 'Phantom Braking #445', collisionType: 'Rear-End (Caused)', severity: 'Minor', speed: 0.0, cause: 'False positive obstacle detection', avoidable: true, vehicleInvolved: 'AutoPilot X1', location: 'Highway 101', recommendations: 'Reduce phantom braking through improved sensor fusion confidence thresholds', status: 'analyzed', description: 'Rear vehicle collided due to phantom emergency braking' }
    ]);
    console.log('Collision Analyses seeded.');

    // Regulatory Compliance (15)
    await RegulatoryCompliance.bulkCreate([
      { name: 'SAE Level 4 Certification', regulation: 'SAE J3016', jurisdiction: 'International', saeLevel: 'Level 4', complianceStatus: 'Compliant', lastAudit: new Date('2024-03-15'), nextAudit: new Date('2024-09-15'), certificationBody: 'SAE International', status: 'active', description: 'SAE Level 4 high driving automation standard compliance' },
      { name: 'FMVSS Crashworthiness', regulation: 'FMVSS 208', jurisdiction: 'United States', saeLevel: 'All Levels', complianceStatus: 'Compliant', lastAudit: new Date('2024-02-20'), nextAudit: new Date('2024-08-20'), certificationBody: 'NHTSA', status: 'active', description: 'Federal Motor Vehicle Safety Standard for occupant crash protection' },
      { name: 'EU AI Act Compliance', regulation: 'EU AI Act 2024', jurisdiction: 'European Union', saeLevel: 'Level 3+', complianceStatus: 'In Progress', lastAudit: new Date('2024-04-01'), nextAudit: new Date('2024-10-01'), certificationBody: 'EU Commission', status: 'active', description: 'European Union Artificial Intelligence Act compliance for high-risk AI systems' },
      { name: 'ISO 26262 ASIL-D', regulation: 'ISO 26262', jurisdiction: 'International', saeLevel: 'All Levels', complianceStatus: 'Compliant', lastAudit: new Date('2024-01-10'), nextAudit: new Date('2024-07-10'), certificationBody: 'TÜV SÜD', status: 'active', description: 'Functional safety for road vehicles at highest integrity level' },
      { name: 'California DMV AV Permit', regulation: 'CA Vehicle Code 38750', jurisdiction: 'California', saeLevel: 'Level 4', complianceStatus: 'Compliant', lastAudit: new Date('2024-05-01'), nextAudit: new Date('2025-05-01'), certificationBody: 'CA DMV', status: 'active', description: 'California autonomous vehicle testing and deployment permit' },
      { name: 'UNECE WP.29 R157', regulation: 'UN R157 ALKS', jurisdiction: 'International', saeLevel: 'Level 3', complianceStatus: 'Compliant', lastAudit: new Date('2024-03-01'), nextAudit: new Date('2024-09-01'), certificationBody: 'UNECE', status: 'active', description: 'UN regulation for Automated Lane Keeping Systems' },
      { name: 'Cybersecurity ISO 21434', regulation: 'ISO/SAE 21434', jurisdiction: 'International', saeLevel: 'All Levels', complianceStatus: 'Compliant', lastAudit: new Date('2024-04-15'), nextAudit: new Date('2024-10-15'), certificationBody: 'ISO/SAE', status: 'active', description: 'Cybersecurity engineering for road vehicles' },
      { name: 'SOTIF ISO 21448', regulation: 'ISO 21448', jurisdiction: 'International', saeLevel: 'Level 3+', complianceStatus: 'In Progress', lastAudit: new Date('2024-02-01'), nextAudit: new Date('2024-08-01'), certificationBody: 'ISO', status: 'active', description: 'Safety of the Intended Functionality for AV systems' },
      { name: 'Euro NCAP AEB Rating', regulation: 'Euro NCAP 2024', jurisdiction: 'European Union', saeLevel: 'All Levels', complianceStatus: 'Compliant', lastAudit: new Date('2024-05-10'), nextAudit: new Date('2025-05-10'), certificationBody: 'Euro NCAP', status: 'active', description: 'European New Car Assessment Programme AEB rating' },
      { name: 'China ICV Standards', regulation: 'GB/T 40429-2021', jurisdiction: 'China', saeLevel: 'Level 3+', complianceStatus: 'Pending', lastAudit: new Date('2024-01-15'), nextAudit: new Date('2024-07-15'), certificationBody: 'MIIT China', status: 'active', description: 'Chinese intelligent connected vehicle classification and standards' },
      { name: 'Japan SIP-adus', regulation: 'SIP-adus Guidelines', jurisdiction: 'Japan', saeLevel: 'Level 4', complianceStatus: 'In Progress', lastAudit: new Date('2024-03-20'), nextAudit: new Date('2024-09-20'), certificationBody: 'Cabinet Office Japan', status: 'active', description: 'Japanese Strategic Innovation Program for automated driving' },
      { name: 'AV Data Recording', regulation: 'NHTSA DSSAD Rule', jurisdiction: 'United States', saeLevel: 'Level 2+', complianceStatus: 'Compliant', lastAudit: new Date('2024-04-05'), nextAudit: new Date('2024-10-05'), certificationBody: 'NHTSA', status: 'active', description: 'Data Storage System for Automated Driving compliance' },
      { name: 'V2X FCC Certification', regulation: 'FCC Part 95', jurisdiction: 'United States', saeLevel: 'All Levels', complianceStatus: 'Compliant', lastAudit: new Date('2024-02-15'), nextAudit: new Date('2025-02-15'), certificationBody: 'FCC', status: 'active', description: 'FCC certification for V2X communication equipment' },
      { name: 'UK AV Legislation', regulation: 'Automated Vehicles Act 2024', jurisdiction: 'United Kingdom', saeLevel: 'Level 4+', complianceStatus: 'Pending', lastAudit: new Date('2024-06-01'), nextAudit: new Date('2024-12-01'), certificationBody: 'UK DfT', status: 'active', description: 'UK Automated Vehicles Act compliance for self-driving authorization' },
      { name: 'Insurance Framework', regulation: 'AV Insurance Directive', jurisdiction: 'International', saeLevel: 'All Levels', complianceStatus: 'Compliant', lastAudit: new Date('2024-05-15'), nextAudit: new Date('2024-11-15'), certificationBody: 'Lloyd\'s of London', status: 'active', description: 'Autonomous vehicle insurance and liability framework compliance' }
    ]);
    console.log('Regulatory Compliance seeded.');

    console.log('\n✅ All seed data inserted successfully!');
    process.exit(0);
  } catch (error) {
    console.error('❌ Seeding failed:', error);
    process.exit(1);
  }
}

seed();
